# Generated by Django 5.0 on 2023-12-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShipGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.IntegerField()),
                ('start_y', models.IntegerField()),
                ('end_x', models.IntegerField()),
                ('end_y', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('instructionlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.instructionlist')),
            ],
        ),
        migrations.CreateModel(
            name='ShipRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipgrid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.shipgrid')),
            ],
        ),
        migrations.CreateModel(
            name='ShipCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('shiprow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.shiprow')),
            ],
        ),
    ]
